### ISSUE TITLE
pip install not working for macOS

### ISSUE THREAD

**Issue by ksanu1998** [DeGirum/PySDKExamples#11]
I am running macOS 12.6.6 (21G646), and have followed the instructions given [here](https://docs.degirum.com/content/pysdk/installation/) to install PySDK. However, looks like the package is not present. Please see the screenshot below.

![MicrosoftTeams-image](https://github.com/DeGirum/Framework/assets/44368780/deaa7958-aa64-4a45-b97b-f0d256abda8b)

**Comment by kvkov** [comment]
Please, specify what platform you are using: M1 or Intel.

Could you try to manually download the wheel matching your platform from PyPi (https://pypi.org/project/degirum/#files) and install it locally, like 'python -m pip install 
degirum-0.8.0-cp39-cp39-macosx_12_0_arm64.whl' ?

**Comment by ksanu1998** [comment]
I am using Intel.

**Comment by ksanu1998** [comment]
Okay, so I tried installing [this](degirum-0.8.0-cp39-cp39-macosx_12_0_x86_64.whl) wheel as suggested and got the following error: 
![Screen Shot 2023-06-06 at 11 16 00 AM](https://github.com/DeGirum/PySDKExamples/assets/44368780/26c33910-50f7-4712-8926-f2e2294d7067)

**Comment by vlad-nn** [comment]
@ksanu1998 , would you please run the following code in your Python and share the results:

```
import distutils
print( distutils.util.get_platform() )
```

**Comment by ksanu1998** [comment]
Changed the commands a little bit. Here's the output:
![Screen Shot 2023-06-06 at 11 24 36 AM](https://github.com/DeGirum/PySDKExamples/assets/44368780/ec325c44-b91d-41d9-beef-ebe4eb40b4ef)

**Comment by vlad-nn** [comment]
@ksanu1998 , it looks like you have very old MscOS version: 10.9. PySDK supports MacOS 12.0.

**Comment by ksanu1998** [comment]
Okay. I've updated my OS version to 12.6.6 (21G646) but looks like Python is using something older. Anyhow, thanks.
