### ISSUE TITLE
Issue when quantizing yolov8 classification model

### ISSUE THREAD

**Issue by luca-depe** [DeGirum/PySDKExamples#63]
Hello!

I tried running  
`python dg_export.py --weights yolov8n-cls.pt --quantize`  
using [dg_export.py](https://github.com/DeGirum/ultralytics_yolov8/blob/master/dg_export.py) but I get the following error:  
`FileNotFoundError: [Errno 2] No such file or directory: 'XXX/datasets/coco128.yaml/train'`.  

While when doing the same for a detection model (such as yolov8.pt) it works great by downloading the sample dataset and quantizing the default model. Do you know why it does not work out of the box also for the classification model?
Thank you very much in advance for your help!
Luca

**Comment by luca-depe** [comment]
Hello!

I did find the issue with this. By changing the following:  
`parser.add_argument('--data', type=str, default='coco128.yaml', help='dataset.yaml path')`
to:  
`parser.add_argument('--data', type=str, default='', help='dataset.yaml path')`  
will allow `TASK2DATA` in `ultralytics.engine.exporter:234` to get the default dataset appropriate for the given task.

**Comment by nklimov23** [comment]
Hello!

That's a nice catch! Indeed, the default provided for the data argument in the parser is for a detection dataset.

**Comment by nklimov23** [comment]
We added the fix that you provided to our Ultralytics repo fork. It is now available. Thank you for finding this for us, and please let us know if you have any other questions!
